brew 'boost'
brew 'chromaprint'
brew 'cmake'
brew 'fftw'
brew 'glew'
brew 'glib'
brew 'google-sparsehash'
brew 'gst-libav'
brew 'gst-plugins-bad'
brew 'gst-plugins-base'
brew 'gst-plugins-good'
brew 'gst-plugins-ugly'
brew 'gstreamer'
brew 'libmtp'
brew 'pkgconfig'
brew 'protobuf'
brew 'protobuf-c'
brew 'qt@5'
brew 'tomahawk-player/homebrew-tomahawkqt5/liblastfm'

# These were added for libgpod support and can probably be removed if/when the
# libgpod package is available.
brew 'wget'
brew 'libplist'
brew 'gnome-common'
brew 'gdk-pixbuf'
brew 'intltool'
brew 'autoconf'
brew 'automake'
brew 'gtk-doc'
