name: all
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  create_release:
    name: Create GitHub Release
    runs-on: ubuntu-18.04
    if: github.ref == 'refs/heads/master'
    needs:
      - build_mingw
    steps:
      - uses: actions/checkout@v1.2.0
      - uses: actions/download-artifact@v2
        with:
          path: release_artifacts
      - name: Create draft pre-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          VERSION=$(echo release_artifacts/**/*.tar.xz | sed -e 's/.*clementine-\(.*\).tar.xz/\1/')
          echo "Version: ${VERSION}"
          assets=()
          for asset in $(find release_artifacts -type f); do
            echo "Adding asset: ${asset}"
            assets+=("-a" "$asset")
          done
          hub release create -p "${assets[@]}" -m "$VERSION" -t "$GITHUB_SHA" "$VERSION"

  build_mingw:
    name: Build Windows Installer
    runs-on: ubuntu-18.04
    container:
      image: eu.gcr.io/clementine-data/mingw-w64:latest
    env:
      PKG_CONFIG_PATH: /target/lib/pkgconfig
    steps:
      - name: Fix liblastfm includes
        run: ln -s /target/include/lastfm /target/include/lastfm5
      - uses: actions/checkout@v1.2.0
      - name: cmake
        working-directory: bin
        run: >
          cmake ..
          -DCMAKE_TOOLCHAIN_FILE=../Toolchain-mingw32.cmake
          -DCMAKE_BUILD_TYPE=Release
      - name: make
        working-directory: bin
        run: make -j2
      - name: Copy output exes
        working-directory: dist/windows
        run: cp ../../bin/*.exe .
      - name: Copy base runtime DLLs
        run: >
          cp
          /usr/lib/gcc/i686-w64-mingw32/*-posix/libgcc_s_sjlj-1.dll
          /usr/lib/gcc/i686-w64-mingw32/*-posix/libstdc++-6.dll
          /usr/i686-w64-mingw32/lib/libwinpthread-1.dll
          dist/windows
      - name: Copy DLL depdendencies
        working-directory: /target/bin
        run: >
            cp
            glew32.dll
            libcdio-19.dll
            libchromaprint.dll
            libcrypto-1_1.dll
            libfaad-2.dll
            libffi-7.dll
            libfftw3-3.dll
            libFLAC-8.dll
            libgcrypt-20.dll
            libgio-2.0-0.dll
            libglib-2.0-0.dll
            libgmodule-2.0-0.dll
            libgmp-10.dll
            libgnutls-30.dll
            libgobject-2.0-0.dll
            libgpg-error-0.dll
            libgpod.dll
            libgstapp-1.0-0.dll
            libgstaudio-1.0-0.dll
            libgstbase-1.0-0.dll
            libgstfft-1.0-0.dll
            libgstnet-1.0-0.dll
            libgstpbutils-1.0-0.dll
            libgstreamer-1.0-0.dll
            libgstriff-1.0-0.dll
            libgstrtp-1.0-0.dll
            libgstrtsp-1.0-0.dll
            libgstsdp-1.0-0.dll
            libgsttag-1.0-0.dll
            libgstvideo-1.0-0.dll
            libgthread-2.0-0.dll
            libhogweed-6.dll
            libiconv-2.dll
            libintl-8.dll
            liblastfm5.dll
            libmms-0.dll
            libmp3lame-0.dll
            libnettle-8.dll
            libogg-0.dll
            liboil-0.3-0.dll
            libopus-0.dll
            liborc-0.4-0.dll
            liborc-test-0.4-0.dll
            libp11-kit-0.dll
            libpcre-1.dll
            libplist.dll
            libprotobuf-17.dll
            libpsl-5.dll
            libssl-1_1.dll
            libsoup-2.4-1.dll
            libspeex-1.dll
            libspotify.dll
            libsqlite3-0.dll
            libtag.dll
            libtasn1-6.dll
            libunistring-2.dll
            libvorbis-0.dll
            libvorbisenc-2.dll
            libxml2-2.dll
            libwavpack-1.dll
            Qt5Concurrent.dll
            Qt5Core.dll
            Qt5Gui.dll
            Qt5Network.dll
            Qt5OpenGL.dll
            Qt5Sql.dll
            Qt5Svg.dll
            Qt5Widgets.dll
            Qt5WinExtras.dll
            Qt5Xml.dll
            zlib1.dll
            ${GITHUB_WORKSPACE}/dist/windows
      - run: mkdir dist/windows/imageformats
      - name: Copy Qt imageformat plugin DLLs
        working-directory: /target/plugins
        run: >
          cp
          imageformats/qgif.dll
          imageformats/qjpeg.dll
          imageformats/qsvg.dll
          ${GITHUB_WORKSPACE}/dist/windows/imageformats
      - run: mkdir dist/windows/platforms
      - name: Copy Qt platforms plugin DLLs
        working-directory: /target/plugins
        run: >
          cp
          platforms/qwindows.dll
          ${GITHUB_WORKSPACE}/dist/windows/platforms
      - run: mkdir dist/windows/styles
      - name: Copy Qt style plugin DLLs
        working-directory: /target/plugins
        run: >
          cp
          styles/qwindowsvistastyle.dll
          ${GITHUB_WORKSPACE}/dist/windows/styles
      - run: mkdir dist/windows/gio-modules
      - name: Copy GIO modules
        run: cp /target/lib/gio/modules/libgiognutls.dll dist/windows/gio-modules
      - run: mkdir dist/windows/gstreamer-plugins
      - name: Copy gstreamer plugins
        working-directory: /target/lib/gstreamer-1.0
        run: >
          cp
          libgstaiff.dll
          libgstapetag.dll
          libgstapp.dll
          libgstasf.dll
          libgstasfmux.dll
          libgstaudioconvert.dll
          libgstaudiofx.dll
          libgstaudioparsers.dll
          libgstaudioresample.dll
          libgstaudiotestsrc.dll
          libgstautodetect.dll
          libgstcdio.dll
          libgstcoreelements.dll
          libgstdirectsound.dll
          libgstequalizer.dll
          libgstfaad.dll
          libgstflac.dll
          libgstgdp.dll
          libgstgio.dll
          libgsticydemux.dll
          libgstid3demux.dll
          libgstid3tag.dll
          libgstisomp4.dll
          libgstlame.dll
          libgstlibav.dll
          libgstmms.dll
          libgstogg.dll
          libgstopus.dll
          libgstopusparse.dll
          libgstpbtypes.dll
          libgstplayback.dll
          libgstreplaygain.dll
          libgstrtp.dll
          libgstrtsp.dll
          libgstsoup.dll
          libgstspectrum.dll
          libgstspeex.dll
          libgsttaglib.dll
          libgsttcp.dll
          libgsttypefindfunctions.dll
          libgstudp.dll
          libgstvolume.dll
          libgstvorbis.dll
          libgstwavpack.dll
          libgstwavparse.dll
          ${GITHUB_WORKSPACE}/dist/windows/gstreamer-plugins
      - name: Build Windows installer
        working-directory: dist/windows
        run: makensis clementine.nsi
      - uses: actions/upload-artifact@v2
        with:
          name: release_mingw
          path: dist/windows/ClementineSetup*.exe
